/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swingguide.panels.jlabel;

import swingguide.helpers.ComponentPanel;
import swingguide.helpers.ComponentTemplate;
import java.awt.Component;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.JLabel;

/**
 *
 * @author Light
 */
public class JLabelPanel_03_State extends ComponentPanel {

    /**
     * Creates new form NewJPanel2
     */
    public JLabelPanel_03_State() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox3 = new javax.swing.JCheckBox();

        jCheckBox3.setText("Disable");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox3)
                .addContainerGap(335, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox3)
                .addContainerGap(270, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox3;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
        return "State";
    }
    
    @Override
    public void setup(Component primaryComponent, ComponentTemplate componentTemplate) {

        JLabel jLabel1 = (JLabel)primaryComponent;
  
        //Disable
        jCheckBox3.setAction(new AbstractAction(jCheckBox3.getText()) {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (jCheckBox3.isSelected()) {
                    jLabel1.setEnabled(false);
                } else {
                    jLabel1.setEnabled(true);
                }
                componentTemplate.setCodeTextArea(
                        "/*  Disable  */\n\n"
                        + "jLabel1.setEnabled(false);\n"
                        + "\n"
                        + "\n"
                        + "/*\n"
                        + "Reset:\n"
                        + "    jLabel1.setEnabled(true);\n"
                        + "*/\n"
                );
            }
        });
    }
}
