/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swingguide.panels.jcombobox;

import java.awt.Color;
import swingguide.helpers.ComponentPanel;
import swingguide.helpers.ComponentTemplate;
import java.awt.Component;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.ButtonModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.plaf.synth.SynthComboBoxUI;

/**
 *
 * @author Light
 */
public class JComboBoxPanel_04_UIModifications extends ComponentPanel {

    private JComboBox jComboBox1;
    private JComboBoxPanel jComboBoxPanel;
    
    /**
     * Creates new form NewJPanel
     */
    public JComboBoxPanel_04_UIModifications() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup3 = new javax.swing.ButtonGroup(){
            @Override
            public void setSelected(ButtonModel m, boolean b){
                if(!b && isSelected(m)){
                    clearSelection();
                } else {
                    super.setSelected(m, b);
                }
            }
        };
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        buttonGroup3.add(jRadioButton5);
        jRadioButton5.setText("Set Padding");

        buttonGroup3.add(jRadioButton4);
        jRadioButton4.setText("Change Arrow Button");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
        return "UI Modifications";
    }
    
    @Override
    public void setup(Component primaryComponent, ComponentTemplate componentTemplate) {
        
        jComboBox1 = (JComboBox)primaryComponent;
        jComboBoxPanel = (JComboBoxPanel)componentTemplate;
        
        //Change Popup Arrow
        jRadioButton4.setAction(new AbstractAction(jRadioButton4.getText()) {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (jRadioButton4.isSelected()) {
                    jComboBox1.setUI(new SynthComboBoxUI() { //or whatever UI you are using
                        @Override
                        protected JButton createArrowButton() {
                            JButton button = super.createArrowButton();
                            JButton newButton = new JButton("<>");
                            newButton.setOpaque(true);
                            newButton.setBackground(Color.GREEN);
                            newButton.setName("ComboBox.arrowButton");
                            newButton.setModel(button.getModel());
                            return newButton;
                        }
                    });
                } else {
                    jComboBox1.setUI(new SynthComboBoxUI());
                }
                componentTemplate.setCodeTextArea(
                        "/*  Change Popup Arrow  */\n\n"
                        + "jComboBox1.setUI(new SynthComboBoxUI() {\n"
                        + "    @Override\n"
                        + "    protected JButton createArrowButton() {\n"
                        + "        JButton button = super.createArrowButton();\n"
                        + "        JButton newButton = new JButton(\"<>\");\n"
                        + "        newButton.setOpaque(true);\n"
                        + "        newButton.setBackground(Color.GREEN);\n"
                        + "        newButton.setName(\"ComboBox.arrowButton\");\n"
                        + "        newButton.setModel(button.getModel());\n"
                        + "        return newButton;\n"
                        + "    }\n"
                        + "});\n"
                        + "\n"
                        + "\n"
                        + "/*\n"
                        + "Reset:\n"
                        + "    jComboBox1.setUI(new SynthComboBoxUI());\n"
                        + "\n"
                        + "Note:\n"
                        + "    Depends on the UI you are using (in this case Synth)\n"
                        + "\n"
                        + "*/\n"
                );
            }
        });

        //Set Padding
        jRadioButton5.setAction(new AbstractAction(jRadioButton5.getText()) {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (jRadioButton5.isSelected()) {
                    jComboBox1.setUI(new SynthComboBoxUI() { //or whatever UI you are using
                        @Override
                        protected void installDefaults() {
                            super.installDefaults();
                            this.padding = new Insets(20, 20, 20, 20);
                        }
                    });
                } else {
                    jComboBox1.setUI(new SynthComboBoxUI());
                }
                componentTemplate.setCodeTextArea(
                        "/*  Set Padding  */\n\n"
                        + "jComboBox1.setUI(new SynthComboBoxUI() {\n"
                        + "    @Override\n"
                        + "    protected void installDefaults() {\n"
                        + "        super.installDefaults();\n"
                        + "        this.padding = new Insets(20, 20, 20, 20);\n"
                        + "    }\n"
                        + "});\n"
                        + "\n"
                        + "\n"
                        + "/*\n"
                        + "Reset:\n"
                        + "    jComboBox1.setUI(new SynthComboBoxUI());\n"
                        + "\n"
                        + "Note:\n"
                        + "    Depends on the UI you are using (in this case Synth)\n"
                        + "*/\n"
                );
            }
        });
    }
}
